// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CreateOrder.proto

package daprexamples

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrderRequest struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	CustomerID           string   `protobuf:"bytes,3,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2476da9e0746a307, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *CreateOrderRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreateOrderRequest) GetCustomerID() string {
	if m != nil {
		return m.CustomerID
	}
	return ""
}

type CreateOrderResponse struct {
	Succeed              bool     `protobuf:"varint,1,opt,name=Succeed,proto3" json:"Succeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2476da9e0746a307, []int{1}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "daprexamples.CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "daprexamples.CreateOrderResponse")
}

func init() { proto.RegisterFile("CreateOrder.proto", fileDescriptor_2476da9e0746a307) }

var fileDescriptor_2476da9e0746a307 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x14, 0x84, 0x5d, 0xc5, 0x6a, 0x9f, 0x05, 0xf1, 0x09, 0xb2, 0x88, 0xc8, 0xba, 0x78, 0xe8, 0x69,
	0x05, 0xfd, 0x05, 0xb6, 0xbd, 0xf4, 0x64, 0x49, 0xfd, 0x03, 0x31, 0x19, 0x44, 0x71, 0x37, 0xf1,
	0x25, 0x11, 0x7f, 0xbe, 0x90, 0x2a, 0x46, 0x84, 0x1e, 0x67, 0x32, 0x79, 0x1f, 0x33, 0x74, 0x32,
	0x17, 0xe8, 0x88, 0x07, 0xb1, 0x90, 0xce, 0x8b, 0x8b, 0x8e, 0x27, 0x56, 0x7b, 0xc1, 0xa7, 0xee,
	0xfd, 0x1b, 0x42, 0xfb, 0x4a, 0x5c, 0x44, 0x14, 0xde, 0x13, 0x42, 0xe4, 0x0b, 0x1a, 0xaf, 0xc4,
	0xd9, 0x64, 0xe2, 0x72, 0x51, 0x57, 0x4d, 0x35, 0x1d, 0xab, 0x5f, 0x83, 0xcf, 0x68, 0x74, 0xdf,
	0xbb, 0x34, 0xc4, 0x7a, 0xb7, 0xa9, 0xa6, 0xfb, 0xea, 0x5b, 0xf1, 0x25, 0xd1, 0x3c, 0x85, 0xe8,
	0x7a, 0xc8, 0x72, 0x51, 0xef, 0xe5, 0x6f, 0x85, 0xd3, 0xde, 0xd0, 0xe9, 0x1f, 0x56, 0xf0, 0x6e,
	0x08, 0xe0, 0x9a, 0x0e, 0xd6, 0xc9, 0x18, 0xc0, 0x66, 0xd4, 0xa1, 0xfa, 0x91, 0xb7, 0x96, 0x26,
	0x39, 0xba, 0x86, 0x7c, 0xbc, 0x18, 0xf0, 0x23, 0x1d, 0x15, 0x07, 0xb8, 0xe9, 0xca, 0x2a, 0xdd,
	0xff, 0x1e, 0xe7, 0x57, 0x5b, 0x12, 0x1b, 0x7a, 0xbb, 0x33, 0xbb, 0xa6, 0xe3, 0x67, 0x0c, 0x10,
	0x1d, 0xb1, 0x99, 0x28, 0xcc, 0xca, 0xd9, 0x56, 0xd9, 0x7a, 0x1a, 0xe5, 0xa7, 0xbb, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbb, 0x98, 0xdb, 0xf1, 0x52, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/daprexamples.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daprexamples.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daprexamples.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CreateOrder.proto",
}
