// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageService.Api;

namespace StorageService.Api.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20191218093621_AddPrimaryKeyToStorage")]
    partial class AddPrimaryKeyToStorage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StorageService.Api.Entities.Storage", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Storage");
                });
#pragma warning restore 612, 618
        }
    }
}
