// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageService.Api;

namespace StorageService.Api.Migrations
{
    [DbContext(typeof(StorageContext))]
    partial class StorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StorageService.Api.Entities.Storage", b =>
                {
                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("char(36)");

                    b.ToTable("Storage");
                });
#pragma warning restore 612, 618
        }
    }
}
