// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DataToPublish.proto

package daprexamples

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorageReduceData struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageReduceData) Reset()         { *m = StorageReduceData{} }
func (m *StorageReduceData) String() string { return proto.CompactTextString(m) }
func (*StorageReduceData) ProtoMessage()    {}
func (*StorageReduceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1af9b1e9162ade5, []int{0}
}

func (m *StorageReduceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageReduceData.Unmarshal(m, b)
}
func (m *StorageReduceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageReduceData.Marshal(b, m, deterministic)
}
func (m *StorageReduceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageReduceData.Merge(m, src)
}
func (m *StorageReduceData) XXX_Size() int {
	return xxx_messageInfo_StorageReduceData.Size(m)
}
func (m *StorageReduceData) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageReduceData.DiscardUnknown(m)
}

var xxx_messageInfo_StorageReduceData proto.InternalMessageInfo

func (m *StorageReduceData) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *StorageReduceData) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*StorageReduceData)(nil), "daprexamples.StorageReduceData")
}

func init() { proto.RegisterFile("DataToPublish.proto", fileDescriptor_e1af9b1e9162ade5) }

var fileDescriptor_e1af9b1e9162ade5 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x76, 0x49, 0x2c, 0x49,
	0x0c, 0xc9, 0x0f, 0x28, 0x4d, 0xca, 0xc9, 0x2c, 0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x49, 0x49, 0x2c, 0x28, 0x4a, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x2d, 0x56, 0xf2, 0xe4,
	0x12, 0x0c, 0x2e, 0xc9, 0x2f, 0x4a, 0x4c, 0x4f, 0x0d, 0x4a, 0x4d, 0x29, 0x4d, 0x4e, 0x05, 0xe9,
	0x10, 0x92, 0xe1, 0xe2, 0x0c, 0x28, 0xca, 0x4f, 0x29, 0x4d, 0x2e, 0xf1, 0x74, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08, 0x08, 0x89, 0x71, 0xb1, 0x39, 0xe6, 0xe6, 0x97, 0xe6, 0x95,
	0x48, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x4e, 0x6a, 0x5c, 0xfc, 0xe9, 0xa9, 0x79,
	0xa9, 0x45, 0x89, 0x25, 0xa9, 0x10, 0xab, 0x8a, 0x9d, 0x50, 0x1d, 0x10, 0x00, 0x16, 0x4c, 0x62,
	0x03, 0x4b, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x40, 0xba, 0xba, 0xc8, 0x9e, 0x00, 0x00,
	0x00,
}
